name: Generate relative strength rankings/watchlists

on:
#  schedule:
#    - cron: '59 22 * * 1-5'  # midnight UTC, which is 6 or 7 PM Central Time
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Set timeout to 60 minutes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch ticker metadata
      run: python rs_ticker_info.py

    - name: Fetch price data
      run: python rs_data.py

    - name: Generate RS rankings
      run: python rs_ranking.py

    - name: Apply screener
      run: python rs_stock_screener.py

    - name: Generate watchlists
      run: python rs_watchlist.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Automated commit of generated files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  retry-job:
    needs: run-script
    runs-on: ubuntu-latest
    if: failure() && needs.run-script.outcome == 'failure' && needs.run-script.conclusion == 'timed_out'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch ticker metadata
      run: python rs_ticker_info.py

    - name: Fetch price data
      run: python rs_data.py

    - name: Generate RS rankings
      run: python rs_ranking.py

    - name: Apply screener
      run: python rs_stock_screener.py

    - name: Generate watchlists
      run: python rs_watchlist.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Automated commit of generated files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
